### ISSUE TITLE
support official image for flashforge FW 2.6.5-2.2.3-20240411

### ISSUE THREAD

**Issue by resixh** [xblax/flashforge_ad5m_klipper_mod#153]
Hi can we get the new version support too?

**Comment by insp1re1** [comment]
> It is coming in the next beta release

taking too long bro

**Comment by consp** [comment]
> taking too long bro

You can edit the file yourself and make it work in that way.

**Comment by resixh** [comment]
can we stop the jokes and trolls?
@KaruroChori  thank you very much for your comment I am looking forward for the release :)

**Comment by insp1re1** [comment]
> can we stop the jokes and trolls? @KaruroChori thank you very much for your comment I am looking forward for the release :)

its simply taking too long bro
