### ISSUE TITLE
Firmware crashing consistently when info button hit.

### ISSUE THREAD

**Issue by jvarrone** [xblax/flashforge_ad5m_klipper_mod#154]
When I hit the little "i" in the lower left hand of the screen, the firmware crashes consistently. Please see the screenshots.

![20240420_101226](https://github.com/xblax/flashforge_ad5m_klipper_mod/assets/3275462/9f76a2e5-78a0-40f4-96da-f1f9e8ed1dda)
![20240420_101236](https://github.com/xblax/flashforge_ad5m_klipper_mod/assets/3275462/61b1b1a1-1f69-4225-92e0-b8953d1ecda8)

**Comment by KaruroChori** [comment]
Is it not what it is supposed to be? I don't use klipperscreen but isn't it the halt function?

**Comment by Tiwatz** [comment]
That is not an I, it is a exclamation mark. And the "info button" is the emergency stop

**Comment by KaruroChori** [comment]
As a I thought, so there is no bug there.

**Comment by jvarrone** [comment]
Sorry, the message it threw about a webhook misled me into believing it was an issue. Perhaps consider making the resulting message more indicative of what actually took place.

 

Thanks for a great mod.

**Comment by KaruroChori** [comment]
This repository does not mod the behaviour of other programs unless it is needed to fit within the limited hardware of this printer.
You should direct this feedback [here](https://github.com/KlipperScreen/KlipperScreen) as they are the maintainers of klipperscreen.
