### ISSUE TITLE
Warning when using Mainsail reported in OrcaSlicer (klipper update to version warning)

### ISSUE THREAD

**Issue by Avpman2** [xblax/flashforge_ad5m_klipper_mod#165]
Getting this warning msg on the Mainsail Device tab in OrcaSlicer:

_Dependency: Klipper
The current Klipper version does not support all features of Mainsail. Update Klipper to at least v0.11.0-257._

**Comment by consp** [comment]
While it might be annoying, there is little which can be done at this time: the klipper mcu code is provided by flashforge and it's currently impossible to update it. The host side already is at the latest compatible version (with some backports from klipper v0.12 in the next release)

Maybe it's possible to suppress the message for now.

**Comment by xblax** [comment]
There is not much we can do about this. It's not worth patching this in the Mainsail code. Afaik beeing a bit behind with the Klipper version doesn't cause any issues and the message does only show up once if acknowledged and checked to not show again.

I'm going to Close it as "Won't Fix".
