### ISSUE TITLE
Error when using Orcaslicer to Mainsail - Code G17 not recognized on touch panel

### ISSUE THREAD

**Issue by Avpman2** [xblax/flashforge_ad5m_klipper_mod#166]
Frequently getting a _Code G17 not recognized_ on the touch display and the Orca console output.

**Comment by consp** [comment]
The next release contains the G17 gcode. Orca generates G17 codes even when the klipper version does not support this (it should 't but does so anyway. You can disable them by setting zhop to normal (see #107)

See #107 #48 for more info.
