### ISSUE TITLE
Extruder rotation distance

### ISSUE THREAD

**Issue by thhdragon** [xblax/flashforge_ad5m_klipper_mod#167]
In the cfg it has 4.4 set as the rotation distance under extruder. the comment says that it uses the stock value but the stock value is 4.7. 
edit: 
that being said, my personal value is about 4.371 so much closer to the one in your cfg i was just mentioning its different than stock

**Comment by consp** [comment]
See #70 almost everyone has ~4.375-4.4mm instead of 4.7. I guess FF used a "safe" value (closing since mention and other discussion).
