### ISSUE TITLE
Corrupted printer.cfg

### ISSUE THREAD

**Issue by KaruroChori** [xblax/flashforge_ad5m_klipper_mod#174]
Some operations performed via the guppyscreen interface resulted in an empty printer.cfg being saved.
I cannot replicate the exact steps which led to this.

Additional investigation is needed.

**Comment by KaruroChori** [comment]
It is possible it relates with https://github.com/xblax/flashforge_ad5m_klipper_mod/issues/93
Or that it is a separate issue.

**Comment by consp** [comment]
> It is possible it relates with #93 Or that it is a separate issue.

Might be the same, might be different. Never had the corruption, do you have the guppyscreen log file (in printer_data/logs)?

**Comment by KaruroChori** [comment]
Sadly no, I reinstalled the mod to work with https://github.com/xblax/flashforge_ad5m_klipper_mod/discussions/8#discussioncomment-9330016

**Comment by consp** [comment]
I'm also pretty sure guppy does not edit printer.cfg but mainsail/klipper does. So I guess it's a klipper/mainsail issue more than any ui issue.

**Comment by KaruroChori** [comment]
Ok I will remove that tag, and close it as duplicate of #93 as they are virtually indistinguishable.
