### ISSUE TITLE
Can't reboot into stock FW

### ISSUE THREAD

**Issue by Avpman2** [xblax/flashforge_ad5m_klipper_mod#182]
Using Fluidd, I can no longer boot into the stock firmware from the macro on the device page with the .05 FW. The only way I can get back into stock is to reboot the printer with a USB stick and the SkipMod file. I haven't tried removing the mod from the same screen.

**Comment by consp** [comment]
That's interesting, could someone else test this as I'm able to boot to stock but I would not rule out my setup is different due to tiny modifications.

**Comment by Avpman2** [comment]
This works, after all. I may have tried it when the printer thought it was busy? I will continue to follow it.
