### ISSUE TITLE
Unable to parse move....

### ISSUE THREAD

**Issue by monkeyWad** [xblax/flashforge_ad5m_klipper_mod#206]
I just ran into this error during a print. I haven't seen this issue before so I wasn't sure where to report it. I'm running the latest release with the updates to guppyscreen that were posted in another issue. Slicer is Oraca 2.1.0-beta. I verified that the machine language is set to klipper and all objects are within the printable area. 

This is the full error about 75% into the print;
Unable to parse move 'G1 X-9.85-46.878 Y-77.4 I4.394 J-3.386 E.04835'

I've attached the gcode I just changed the extension to .txt so gitlab wouldn't complain. Thanks!
[Stacking game ninja mice v6_PLA_2h59m.txt](https://github.com/user-attachments/files/15753834/Stacking.game.ninja.mice.v6_PLA_2h59m.txt)

**Comment by KaruroChori** [comment]
It seems like orcaslicer had some bugs in that version. Others reported a similar parsing problem. 
https://github.com/xblax/flashforge_ad5m_klipper_mod/issues/189

This should be reported in the orcaslicer repository if it is still valid for their latest release.
