### ISSUE TITLE
z_offset get ignored - regardless of whether saved in overrides, or is the original [probe] version

### ISSUE THREAD

**Issue by DougJoseph** [xblax/flashforge_ad5m_klipper_mod#224]
When the Klipperscreen macro for Z calibrate is done, it remarks out (comments out) the original default -0.25 value in a [probe] section in printer.cfg, and adds an override value of "#*# z_offset = -0.xxx" — 

...but I cannot seem to get changes to z_offset to make any difference, regardless of whether the value is in the overrides section, or when the original value gets uncommented and edited.

**Does not work for me (as far as I can tell) for Z_OFFSET**
```
[probe]
#z_offset: -0.25

#Fake profile, it must be calibrated if desired.
[skew_correction skew_profile]
xy_skew = 0.0
xz_skew = 0.0
yz_skew = 0.0

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [input_shaper]
#*# shaper_type_x = mzv
#*# shaper_freq_x = 61.8
#*# shaper_type_y = zv
#*# shaper_freq_y = 50.8
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	-2.580000, -2.695000, -2.792500, -2.880000, -2.967500
#*# 	-2.625000, -2.707500, -2.755000, -2.857500, -2.960000
#*# 	-2.602500, -2.597500, -2.595000, -2.722500, -2.885000
#*# 	-2.462500, -2.437500, -2.450000, -2.545000, -2.797500
#*# 	-2.167500, -2.192500, -2.137500, -2.265000, -2.592500
#*# x_count = 5
#*# y_count = 5
#*# mesh_x_pps = 3
#*# mesh_y_pps = 3
#*# algo = bicubic
#*# tension = 0.2
#*# min_x = -105.0
#*# max_x = 105.0
#*# min_y = -105.0
#*# max_y = 105.0
#*#
#*# [probe]
#*# z_offset = -0.160
```

**Also does not work (as far as I can tell) for Z_OFFSET**
```
[probe]
z_offset: -0.16

#Fake profile, it must be calibrated if desired.
[skew_correction skew_profile]
xy_skew = 0.0
xz_skew = 0.0
yz_skew = 0.0

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [input_shaper]
#*# shaper_type_x = mzv
#*# shaper_freq_x = 61.8
#*# shaper_type_y = zv
#*# shaper_freq_y = 50.8
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	-2.580000, -2.695000, -2.792500, -2.880000, -2.967500
#*# 	-2.625000, -2.707500, -2.755000, -2.857500, -2.960000
#*# 	-2.602500, -2.597500, -2.595000, -2.722500, -2.885000
#*# 	-2.462500, -2.437500, -2.450000, -2.545000, -2.797500
#*# 	-2.167500, -2.192500, -2.137500, -2.265000, -2.592500
#*# x_count = 5
#*# y_count = 5
#*# mesh_x_pps = 3
#*# mesh_y_pps = 3
#*# algo = bicubic
#*# tension = 0.2
#*# min_x = -105.0
#*# max_x = 105.0
#*# min_y = -105.0
#*# max_y = 105.0
```

I tried:

[probe]
z_offset = -0.16

[probe]
z_offset = -0.15

[probe]
z_offset = -0.10

And no matter what I do, I cannot see a bit of difference in the actual Z offset when printing.

PS: I also then went the other direction, trying this:

[probe]
z_offset = -0.30

and THIS!

[probe]
z_offset = -1.3

...And still no change whatsoever.

**Comment by DougJoseph** [comment]
It may be that I don't properly understand what the Z_Offset value is used for. 

According to one Redditor in this post:  

https://www.reddit.com/r/klippers/comments/h0cb1e/comment/ftlnhxk/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

He suspects the value is only used during probing, and since I don't always re-probe on every print job (I home to the endstop, not a touch off with the nozzle probing the bed) it may well be that what the machine perceives based on the end of the "Z calibrate" process (in which I manually lower the nozzle until the paper is barely scratched by the nozzle) is the only thing it goes by, until the next time it probes to the bed. But how would I invoke a probe to the bed that is not yet another Z calibrate with the paper scratch process again?

There's possibility for a lot of variance between each manual paper scrape test. The first time I did it on this new (third) AD5M, I did not pay attention to get it at the "barely scrape" point because I thought, "I'll just edit in the config file." I had it pretty snug, and it saved an auto-calculated value of -0.16. After reading the above Reddit post about suspecting it only gets referenced during probing, I repeated Z calibrate, and I paid attention, getting it to just barely scrape the paper, and it saved a new value of -.31. However, on my next attempt at a print job, that still made absolutely no difference. The nozzle was too high.

At this point, experienced Klipper users reading this are thinking, "Why don't you just use fine tuning?"  (aka baby stepping).

I'll not only explain why I had not been using fine tuning / baby stepping, and what I finally just now learned, after months of using Klipperscreen on the AD5M.

REASON: The Klipperscreen GUI on the AD5M does not show any "Save values" button on the fine tuning (baby stepping) screen. When you go back out of the fine tuning screen, there is **still** "Save values" button — no option for updating things so you don't have to keep doing it.

WHAT I JUST SAW for the first time: after I cancelled the job, I finally got shown a button to save values (presumably from the fine tuning). I did not at that time save the values because I had been a bit over zealous, and I wanted to redo it. I am in hopes that the same button gets shown after the job completes, at which time I plan to punch the button with prejudice and careful attention to seeing it done.

This leads me to: if the "Values saved" from fine tuning don't get stored in an adjustment to the Z_Offset value, then where in the Klipper world do those fine tuning values get saved? Because that's what I should have been editing!

Thanks for any clarity, corrections, or advice anyone can give.

PS: If I eventually prove and conclude that fine-tuning + saving values actually accomplished what I'm after, I will mark this post as the solution! :-)

**Comment by DougJoseph** [comment]
**I may be onto something.  In macros.cfg, the macro section labelled**

`[gcode_macro START_PRINT]`

... contains this line of code:

`SET_GCODE_OFFSET Z=0.0  ; reset the G-Code Z offset (adjust Z offset if needed)`

And according to these two posts:
* https://klipper.discourse.group/t/klipper-not-applying-z-offset-to-future-prints/13317/18
* https://klipper.discourse.group/t/klipper-not-applying-z-offset-to-future-prints/13317/19

**... the above line of code in the macro, invalidates my saved z_offset in printer.cfg.**

**Comment by xblax** [comment]
Hey @DougJoseph, I think you are mixing up some things:

Probe Z-Offset and G-Code Z-Offset are separate offsets. G-Code Z-Offset is used to fine-adjust for a specific print, i.e. to adjust offset during print. Resetting the G-Code Z-Offset before printing has nothing to with Probe Z-Offset.

Probe Z-Offset is taken into Account when Probing. After you change this value, then re-do your bed mesh - otherwise it does not have any effect.

 Z_OFFSET_APPLY_PROBE should not go into START_PRINT macro, this would just mess things up.

**Comment by DougJoseph** [comment]
@xblax Thanks! I will change my approach and see if I can get success.

**Comment by DougJoseph** [comment]
> Probe Z-Offset is taken into Account when Probing. After you change this value, then re-do your bed mesh - otherwise it does not have any effect.

Dude, you are awesome. That did the trick. All I had to do was repeat the mesh probe process after setting the Z_Offset, and it finally has the nozzle at the height it needs to be! Thank you so much. 

If there is a way to mark your answer as the solution, I would like to.  I don't see how to do that yet.
