### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by Sunflex616** [xblax/flashforge_ad5m_klipper_mod#58]
Hey! 
I just tried to install the mod onto my A5 Pro. Unfortunately, both images fail with the same error message displayed in the log.
Is there anything obvious I'm missing or have I just stumbled upon something? 

### **klipper_mod_install.log**

```
+ '[' Adventurer5MPro '!=' Adventurer5M ']'
+ '[' Adventurer5MPro '!=' Adventurer5MPro ']'
+ '[' 0024 '!=' 0023 ']'
+ '[' 0024 '!=' 0024 ']'
++ uname -m
+ '[' armv7l '!=' armv7l ']'
++ cat /root/version
+ FF_VERSION=2.4.5
+ '[' 2.4.5 '!=' 2.4.5 ']'
+ MOD_INIT_FILE=/etc/init.d/S00klipper_mod
+ MOD_INIT_FILE_OLD=/etc/init.d/S90klipper_mod
+ MOD_DIR=/data/.klipper_mod
+ CHROOT_DIR=/data/.klipper_mod/chroot
+ xzcat /data/update/img/install_start.img.xz
+ rm -f /etc/init.d/S00klipper_mod
+ rm -f /etc/init.d/S90klipper_mod
+ rm -rf /data/.klipper_mod/chroot
++ df /data
++ tail -1
++ tr -s ' '
++ cut '-d ' -f4
+ FREE_SPACE=5056072
+ MIN_SPACE=524228
+ '[' 5056072 -lt 524228 ']'
+ mkdir -p /data/.klipper_mod/chroot
+ tar -xf - -C /data/.klipper_mod/chroot
+ xz -dc /data/update/chroot.tar.xz
xz: corrupted data
tar: short read
+ '[' 1 -eq 0 ']'
+ error_handler
+ xzcat /data/update/img/install_fail_error.img.xz
+ sync
+ exit 0
```

**Comment by xblax** [comment]
> + xz -dc /data/update/chroot.tar.xz
> xz: corrupted data
> tar: short read

This might indicate the update file is corrupted. Maybe try to again download and copy it to the USB drive. Use the 'safely remove' mechanism.

**Comment by KaruroChori** [comment]
Can you compare the md5 between the file you downloaded and the one on the USB?
Please, link the one you selected so that I can compute the hash on it and check if they are the same.

**Comment by xblax** [comment]
```
md5sum Adventurer5M-KlipperMod-v00.03-beta.tgz
8a059ec1e4cbcc81fcc54f59ca69d3eb  Adventurer5M-KlipperMod-v00.03-beta.tgz
```
Just checked the file as I locally build it and downloaded again from GitHub to confirm it's the same.

Did you maybe try to unpack the archive? Just the 'Adventurer5M-KlipperMod-v00.03-beta.tgz' should go on the the flash drive. You also can unpack it if you want to but be ware that this is just a tar file despite the name (required due to flashforge compatibility). Then if you check the chroot.tar.xz it should be

```
6b493cea6c36bd9f741493fd0d1c4f71  chroot.tar.xz
```

**Comment by KaruroChori** [comment]
d59f160202d7507b09a635bb62c79c79 as well.

**Comment by xblax** [comment]
> d59f160202d7507b09a635bb62c79c79

Can also confirm this. Did just now test install the KlipperScreen variant. That worked without issues.
It it the same checksum after you unplugged the flash drive?

Try to unpack the archive and copy the contents to the usb drive, that works as well. Then you have:
```
chroot.tar.xz
flashforge_init.sh
img
```
If it still fails you can edit flashforge_init.sh to run md5sum just before unpacking the archive. Than we see the checksum in the log.

**Comment by xblax** [comment]
Try:

> mkdir -p $CHROOT_DIR
> **md5sum $WORK_DIR/chroot.tar.xz**
> xz -dc $WORK_DIR/chroot.tar.xz | tar -xf - -C $CHROOT_DIR
> sync

**Comment by xblax** [comment]
For the KlipperScreen variant that should show 
`144d2723027c639afa731abcdea87de3  chroot.tar.xz`

**Comment by KaruroChori** [comment]
>Loading /usr/share/midis/getitem.mid ...
Track:  Game: Zelda, Link's Awakening

I can already see nintendo lawyers DMCAing this repository out of existence :(.

**Comment by xblax** [comment]
That looks normal now. Seems to be Schroedingers USB drive. Behaves differently when you look ...
No clue at the moment what could cause this. I think I had noticed a corrupted chroot.tar.xz once during development, but not sure if related.

**Comment by consp** [comment]
> I can already see nintendo lawyers DMCAing this repository out of existence :(.

File was in a free to use repo, so should be fine since midi's are considered new expressions. If it's a problem I'll write a new one myself.

**Comment by xblax** [comment]
Added md5sum calculation to the install script. Checksum will be printed in the log by default with the next release. Maybe that helps us to understand the issue better if it should appear again.

@Sunflex616 Maybe you can let us know if it's still a reoccurring issue for you.
